defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: murals
    values:
      layout: mural
collections:
  murals:
    output: true
    permalink: /programs/murals/:name/
markdown: kramdown
sass:
  compressed: true
  sass_dir: _sass
exclude:
  - .circleci
  - .gitignore
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
