defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown
sass:
  compressed: true
  sass_dir: _sass
exclude:
  - .circleci
  - .gitignore
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
