version: 2
jobs:
  build:
    docker:
       - image: thefuturesfund/walls-site-circleci
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: build site
          command: bundle exec jekyll build
      - run:
          name: deploy site
          command: |
            if [ "${CIRCLE_BRANCH}" == "beta" ]; then
              aws s3 sync ./_site/ s3://beta.thewallsproject.org/
            elif [ "${CIRCLE_BRANCH}" == "www" ]; then
              aws s3 sync ./_site/ s3://www.thewallsproject.org/
            fi
